name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install dependencies
        run: |
          cd demo
          npm install

      - name: Build project
        run: |
          cd demo
          npm run build

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v4  # Updated to v4
        with:
          name: production-files
          path: ./demo/dist

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4  # Updated to v4
        with:
          name: production-files
          path: ./demo/dist

      - name: Deploy to GitHub
